---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pdvd-arangodb.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  serviceName: {{ include "pdvd-arangodb.name" . }}
  selector:
    matchLabels:
      app:  {{ include "pdvd-arangodb.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "pdvd-arangodb.name" . }}
    spec:
      containers:
        - name: {{ include "pdvd-arangodb.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8529
          env:
            - name: ARANGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: arangodb
                  key: DBPassword
          volumeMounts:
          - name: arangodata
            mountPath: /var/lib/arangodb3
          - name: arangoappsdata
            mountPath: /var/lib/arangodb3-apps
      {{ if not (and (contains "gke" (.Capabilities.KubeVersion.Version | toString)) (contains "eks" (.Capabilities.KubeVersion.Version | toString))) }}
      volumes:
      - name: arangodata
        hostPath:
          type: DirectoryOrCreate
          path: /arangodata  # matches kind containerPath in Kind Cluster.yaml
      - name: arangoappsdata
        hostPath:
          type: DirectoryOrCreate
          path: /arangoappsdata  # matches kind containerPath in Kind Cluster.yaml
      {{ end }}
  {{ if or (contains "gke" (.Capabilities.KubeVersion.Version | toString)) (contains "eks" (.Capabilities.KubeVersion.Version | toString)) }}
  volumeClaimTemplates:
  - metadata:
      name: arangodata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ortelius-sc"
      resources:
        requests:
          storage: 100Gi
  - metadata:
      name: arangoappsdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ortelius-sc"
      resources:
        requests:
          storage: 10Gi
  {{ end }}
