apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "microservice.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  serviceName: {{ include "microservice.name" . }}
  selector:
    matchLabels:
      app:  {{ include "microservice.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "microservice.name" . }}
    spec:
      containers:
        - name: {{ include "microservice.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8529
          env:
            - name: ARANGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: arangodb
                  key: DBPassword
          volumeMounts:
          - name: arangodata
            mountPath: /var/lib/arangodb3
          - name: arangoappsdata
            mountPath: /var/lib/arangodb3-apps
      volumeClaimTemplates:
      - metadata:
          name: arangodata
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "ortelius-sc"
          resources:
            requests:
              storage: 10Gi
      - metadata:
          name: arangoappsdata
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "ortelius-sc"
          resources:
            requests:
              storage: 1Gi